version: '3.6'

services:
  utility-dashboard:
    container_name: utility-dashboard
    image: utility-dashboard:latest
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: C:\projects\utility\devops-utility\config\dashboard\application.properties
        target: /config/application.properties
    restart:
      on-failure
  utility-converter:
    container_name: utility-converter
    image: utility-converter:latest
    ports:
      - 8081:8080
    volumes:
      - type: bind
        source: C:\projects\utility\devops-utility\config\converter\application.properties
        target: /config/application.properties
    restart:
      on-failure
  utility-bundlechecktool:
    container_name: utility-bundlechecktool
    image: utility-bundlechecktool:latest
    ports:
      - 8082:8080
    volumes:
      - type: bind
        source: C:\projects\utility\devops-utility\config\bundlechecktool\application.properties
        target: /config/application.properties
    restart:
      on-failure
  utility-diagnostictool:
    container_name: utility-diagnostictool
    image: utility-diagnostictool:latest
    ports:
      - 8083:8080
    volumes:
      - type: bind
        source: C:\projects\utility\devops-utility\config\diagnostictool\application.properties
        target: /config/application.properties
    restart:
      on-failure